cayangtuu/twitter-api

- migrations/20190115071418-create-followship.js
- migrations/20190115071419-create-like.js
- migrations/20190115071420-create-reply.js
- migrations/20190115071420-create-tweet.js
- migrations/20190115071421-create-user.js
- models/followship.js
- models/like.js
- models/reply.js
- models/tweet.js
- models/user.js
1. 編輯了models檔及migrations檔案
2. Models檔案皆已通過測試檔測驗
3. 唯User Story中的預設山水圖因找不到URI連結，故暫時沒寫進user-migrations檔之預設值中
> feat: create db and migrations

- migrations/20190115071421-create-user.js
設定山景圖為User model中cover-page欄位之預設值(defaultValue)
> fix: add default value of cover-page to User model

- Procfile
- config/config.json
第一次Heroku雲端部署，包含建立資料庫與種子資料
網頁名稱：https://aqueous-tor-51893.herokuapp.com/
> feat: modify config for heroku

- controllers/tweet-controller.js
- routes/modules/tweets.js
> feat: add one tweet API

- controllers/admin-controller.js
- routes/modules/admin.js
- 新增管理員能瀏覽全部推文功能
- 推文內容需只顯示50字
- 推文照最新發表時間排列
> Feature/ admin can get all tweets with description limited to 50

- controllers/user-controller.js
- routes/index.js
> feat: add top ten users api

- controllers/user-controller.js
- routes/modules/users.js
- 新增API: GET /api/users/:id/likes(按讚的內容照按讚時間排列，最新按讚先，若該特定使用者無按讚內容回傳空陣列)
- 調整top10檔案中req.user為getUser(req)
> Feature/ get all contents the user like

- controllers/user-controller.js
- routes/modules/users.js
- 新增API(GET /api/users/:id/followings)(下一個PR再補上名單排序方式)
> Feature/ add the function to get all followings of the user

- controllers/followship-controller.js
新增追蹤者與刪除追總者兩支API，皆新增追蹤者是否為使用者自己之錯誤判斷
> feat: add follower shouldn't follow himself error message

- controllers/user-controller.js
- routes/modules/users.js
- 新增API: GET /api/users/:id/followers
- 調整API: GET /api/users/:id/followers跟GET /api/users/:id/followings名單內容排列方式(依 like 紀錄成立的時間，愈新的在愈前面)
> Feature/ add funtion to get all followers of the user

- controllers/user-controller.js
- routes/modules/users.js
- 新增API: GET /api/users/:id/tweets
- 新增API: GET /api/users/:id/replied_tweets
- 新增API: GET /api/users/:id/followings中錯誤訊息(error:此使用者不存在!)
> Feature/ add two API to get tweets and replies of the user

- controllers/user-controller.js
- 新增API (GET /api/users/:id/followers)中錯誤訊息(error: 此使用者不存在!)
> feature/ add error check of the user followers list

- controllers/tweet-controller.js
- controllers/user-controller.js
- 新增isLiked的檢查在兩支API(GET /api/users/:id/tweets 及 GET /api/users/:id/likes)
- 調整變數命名統一為likeCounts
> Feature/ add isLiked check to getUserLikes and getUserTweets

- controllers/tweet-controller.js
新增isLiked 輸出變數 至GET api/Tweets 及 GET api/Tweets/:id API中
調整變數命名統一為likeCounts
> fix: add isLiked boolean to getTweet API

- controllers/user-controller.js
> Fix/ convert the isliked to boolean

- controllers/tweet-controller.js
1.  更改isLiked邏輯並將值改為boolean
2.  更改get tweet-replies之排列方式，創建時間先者排序在前
3.  更改post tweet-replies之輸出user變數為User
> fix: modify isLiked function and order of tweet-replies, etc

- controllers/user-controller.js
- 新增GET /api/users/:id/likes回傳內容中tweet建立跟更新時間
> Feature/adjust getUserLikes response(add Tweet createdAt and updatedAt)

- controllers/admin-controller.js
- controllers/user-controller.js
> fix: add catch error

- controllers/user-controller.js
- 因應前端資料需求，在getUser回傳資料中增加tweetCounts變數
> Feature/ add tweetCounts to getUser

- controllers/user-controller.js
> fix/ admin cannot in the top ten list

- controllers/user-controller.js
> fix: adjust signup

- controllers/user-controller.js
- 調整 user followers 中 isFollowed
> fix:/ adjust user followers
